### ISSUE TITLE
Add a way to view the highest clear from an individual doctor

### ISSUE THREAD

**Issue by CollageBro** [akgcc/akgcc.github.io#1]
As far as I know there is a way to find the duplicates (hence the "Other clears by this doctor:" when you click on some clear) but there is no way to just show the highest clear of each doctor.

(I know I could just use the scraper and the use use the json to find the duplicates with a script but it would be neat if it was integrated on the website itself)

**Comment by akgcc** [comment]
When I have some free time I'll add it. For now you can run this in the console to hide all duplicates except the latest one (which should be close to what you want). `Array.from(document.getElementsByClassName('cardContainer')).forEach(c=>{if(c.getAttribute('data-dupe')||null !== null) c.classList.add('hidden')})`

**Comment by CollageBro** [comment]
It works, there is just the edge case where someone hypothetically uploads a max risk week 1 clear but during week 2 they upload niche clears. Anyways, thanks for the help.

**Comment by akgcc** [comment]
I changed the way duplicates are grouped, so this is now possible. You can use this one-liner to do exactly what you want: ``Object.keys(dupe_groups).forEach(g=>Array.from(document.querySelectorAll(`.cardContainer[data-dupe="${g}"]`)).sort(x=>cardData[x.id].risk).slice(1).forEach(d=>d.style.display='none'))``
