### ISSUE TITLE
Story reader sometimes do not display multiline messages.

### ISSUE THREAD

**Issue by watiko** [akgcc/akgcc.github.io#2]
Although `story.js` determines the end of a multiline if args.end is present, there are cases where args.end is not present.
https://github.com/akgcc/akgcc.github.io/blob/4a5e2576245c589764d325ff005c8d96859082b7/cc/js/story.js#L1180

example: https://github.com/Kengxxiao/ArknightsGameData_YoStar/blob/3356013dce86352f76d49cd6018f4ba7e83ae748/en_US/gamedata/story/activities/act30side/level_act30side_01_beg.txt#L287-L290

**Comment by akgcc** [comment]
Good find, thank you!
